### ISSUE TITLE
Obvious fake patient names

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#100]
@awong-dev 
Suggest using obvious fake patient data within the interim system.  After accessing the web link, it appears that the SCI Demo has real patient information, even though it does not.  Using well known cartoon characters or even a test patient naming convention will help mitigate any confusion. 

Recommend using obvious fictitious names or test patients like:

| Last Name | First Name |
| --- | --- |
| Lantern | Green |
| Man | Super |
| Mouse | Minnie |
| Duck | Daffy |
| Patient01 | Test |
| Patient02 | Test |

**Comment by awong-dev** [comment]
Thanks for pointing this out. Is this a rule or a preference? And who do we want to avoid confusing? Just ourselves?

The data is auto-generated fake stuff using the standard "Faker" tools in Ruby. There's a good testing reason to use stuff that's closer to reality so I'd like to know what we are gaining if we are going to trade that off.

**Comment by iamkevinscott** [comment]
It is a rule.  I will try and find and reference the VA policy or handbook.  From my previous experience with the DoD, the developers and sys admins had to use fictitious names and the first three digits (prefix) of any SSN would begin with "000" or "666".  Not trying to throw a wrench in everyone's work, just trying to keep us compliant.  More to follow...

**Comment by awong-dev** [comment]
no need to cite a rule. I believe you. Will fix.

**Comment by iamkevinscott** [comment]
If you all are using a "Fake Generator" for data, that may be sufficient for now.  Will these be removed once the system is launched?  Perhaps after the launch of the Interim System, test patients can be generated using the methodology I provided above.  These are used for training and demo purposes.

**Comment by awong-dev** [comment]
Cool. I can easily do something like suffix all names with the word "Fake" or something. Similarly, I can zero out the first 3 bits of the SSN.

All this data will definitely be removed. It's just there so we have something to play with.

**Comment by iamkevinscott** [comment]
Works for me...closing this thread
