### ISSUE TITLE
Add missing fields required for reports

### ISSUE THREAD

**Issue by huttj** [department-of-veterans-affairs/SCIInterim#112]
Various fields aggregated in the reports are not included in the model. Examples include gender and whether the injury was traumatic (vs. non-traumatic).

Some of the aspects of the reports may be represented in the data, but I do not know how to derive them. For example, high vs. low tetraplegia, paraplegia, ASIA D, etc.

It seems that whether the cause was traumatic injury or something non-traumatic can be derived from the etiology. However, that field should probably be changed to an enum to make the calculation more feasible.

**Comment by kathypham-gov** [comment]
@awong-dev Not sure where this particular issue fits in with our current development plan and field clarification with Phil/Peter/Sophia.

**Comment by awong-dev** [comment]
This is being preempted by new meta bug #288
