### ISSUE TITLE
User real station names.

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#115]
Albuquerque
Augusta
Boston
Bronx
Cleveland
Dallas
East Orange
Hampton
Hines
Houston
Long Beach
Memphis
Miami
Milwaukee
Minneapolis
Palo Alto
Richmond
St Louis
Seattle
San Antonio
San Diego
San Juan
Tampa
Syracuse

**Comment by awong-dev** [comment]
Taken from 2015_AE_Outcomes_Data_Collection_spreadsheet.xls

**Comment by huttj** [comment]
@awong-dev Are these part of the patient or the eoc model? Or both?

**Comment by awong-dev** [comment]
Not sure...patient for now?

**Comment by huttj** [comment]
Can do.

I would expect that patients have a station they're assigned to (which can change), and that evaluations are done at stations.

For the purposes of reporting, I would imagine that you would want them on both. You could then answer questions like, "What is the current status of people at station _X_," and "What are the cumulative outcomes of annual evaluations administered at station _X_?"

What do you think?

**Comment by kathypham-gov** [comment]
Not sure where this fields fit with VAMC, Facility, or Hub. @awong-dev?

**Comment by awong-dev** [comment]
Preempted by #142. Closing.
