### ISSUE TITLE
Multiple users editing same patient

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#129]
Just thought of this after the call with MIO Coordinators: How does the system deal with multiple users editing one patient?

**Comment by kathypham-gov** [comment]
Not sure if we care about this.

**Comment by awong-dev** [comment]
Last one wins. Update is atomic to the whole user. We need to create an audit log of changes per patient which should be "good enough" for the basic system. Opening new issue #207 for creating audit log.
