### ISSUE TITLE
Update Patient/Personal Info: First Name, Last Name - madatory

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#131]
Mandatory
Text

**Comment by kathypham-gov** [comment]
First name and last name have already been added.

**Comment by kathypham-gov** [comment]
Make sure this field is mandatory. Keeping open until confirmed.

**Comment by emilyville** [comment]
![screen shot 2015-07-14 at 10 32 43 am](https://cloud.githubusercontent.com/assets/1307774/8680078/c2ecba30-2a13-11e5-82eb-5e17379a06b4.png)

While it does appear they are mandatory - the error message needs to be changed to reflect this more accurately. Suggest changing to:
"Please enter patient's first name"
"Please enter patient's last name"

**Comment by awong-dev** [comment]
Done.
