### ISSUE TITLE
Update Patient/Personal Info: DOB - mandatory

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#134]
MM/DD/YYYY
Date - datepicker

**Comment by kathypham-gov** [comment]
Update Dob to DOB.

**Comment by kathypham-gov** [comment]
Need to add force format instead of free text?

**Comment by emilyville** [comment]
Yes! And also will remove calendar picker for historical dates. Assigning this to myself.

**Comment by emilyville** [comment]
this is done!
