### ISSUE TITLE
Update Patient/Personal Info: SCIDO ID

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#137]
Text
(Not sure what this is - Kathy)

**Comment by awong-dev** [comment]
We need to normalize the naming.

The "SCIDO ID" concept is just the id used in the SCIDO database.
The "CDW ID" concept is the same thing, but for the copy in CDW
We have our own @patient.id which is a _third_ id in the system.

The first two are read only and comes from data import.

**Comment by awong-dev** [comment]
It's displayed.
