### ISSUE TITLE
General: Boolean fields rendered incorrectly by simpleform and CSS styles.

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#139]
Check Box: Check If Yes

Check this box if they are subscribed to myhealthevet secured messaging.

**Comment by kathypham-gov** [comment]
![image](https://cloud.githubusercontent.com/assets/10030313/8706479/c7db2d66-2ae4-11e5-84c7-f979e9adec72.png)

**Comment by emilyville** [comment]
this is done!
