### ISSUE TITLE
Update Patient/Travel: Travel Eligibility 

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#141]
Drop Down:
- Not Eligible
- < 30% more
- VA Pension
- Benefit Travel Waiver

If Benefit Travel Waiver, then have a field for Exception Expiration Date

**Comment by awong-dev** [comment]
Work to do: `Exception Expiration Date` always displayed. Needs to be conditional on selecting `Benefit Travel Waiver`

**Comment by emilyville** [comment]
this is done! Conditional formatting still needs to happen. will make new issue for that.
