### ISSUE TITLE
Patient/VA Status: Assigned VAMC/HUB/all-the-station-names.

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#142]
Drop Down: Station # - See Stations list in the spreadsheet

In Assigned SCI Hub and Preferred SCI Hub: Change Location Name to Station Number
VAMC List
VA Facility list

Waiting on Peter to confirm the lists for VAMC and facility

**Comment by awong-dev** [comment]
Need to add the list of stations so that this actually a drop-down.

**Comment by kathypham-gov** [comment]
Waiting on Peter to clarify list.

**Comment by emilyville** [comment]
should be addressed with issue #292, but still waiting on locations.

**Comment by kathypham-gov** [comment]
Kathy will check Peter's list 08/12/2015 and update.

**Comment by awong-dev** [comment]
Use https://github.com/department-of-veterans-affairs/SCIInterim/blob/master/doc/facilities-hubs-VAMCs.xlsx for list.

**Comment by emilyville** [comment]
@awong-dev I think this makes more sense for you. Let mr know if you prefer otherwise.
