### ISSUE TITLE
Update Patient/Primary Care: Non-VA Facility

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#147]
Name of Facility - Text
Phone Number - Text
Fax Number - Text
PCP First Name - Text
PCP Last Name - Text

**Comment by kathypham-gov** [comment]
@awong-dev  @emilyville: The current published UI has "non va facility contact." This is not in the spreadsheet so I am not sure what it is.

**Comment by awong-dev** [comment]
Need to reconcile with latest spreadsheet.

Alpha launch sounds right.

**Comment by kathypham-gov** [comment]
Update "Non va facility contact" to Non VA Facility Contact Name"

**Comment by emilyville** [comment]
@kathytpham I think this is done, or are we missing a contact name in addition to physician name?

also, merging with issue #292

**Comment by kathypham-gov** [comment]
Almost done! Update "Number" to be "Phone Number." Then done!
