### ISSUE TITLE
Update Patient/Primary Care: VA Facility

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#148]
Name of Facility - Station Number - see spreadsheet
PCP First Name
PCP Last Name

**Comment by awong-dev** [comment]
Need to reconcile with spreadsheet.

**Comment by awong-dev** [comment]
Related to #142

**Comment by emilyville** [comment]
still need facility lists, merging with issue #292

**Comment by kathypham-gov** [comment]
PCP First Name and Last name done. Need to Facility List. Kathy will review Peter Hunt's facility list and update 08/12/2015.
