### ISSUE TITLE
Add Patient/Primary Care: Principle PCP

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#149]
Label: Which is your principle primary care physician?
Radio: VA, Non-VA

**Comment by emilyville** [comment]
@kathytpham I believe this should go at the top of this block and eventually dictate what shows below?

![screen shot 2015-07-15 at 2 59 13 pm](https://cloud.githubusercontent.com/assets/1307774/8710901/188d71e8-2b02-11e5-946f-3a81290cec63.png)

**Comment by emilyville** [comment]
Actually, we crossed this out after speaking with Peter. Now I am confused. 
![screen shot 2015-07-15 at 3 02 58 pm](https://cloud.githubusercontent.com/assets/1307774/8710976/a9e82340-2b02-11e5-8fc0-28b8ebb0e490.png)

Suggest closing this issue, or double checking with Peter that this is again a thing we need - or just a spreadsheet version control issue.

**Comment by kathypham-gov** [comment]
Confirmed with Peter: Keep "Which is your principle primary care physician: VA or NON-VA?"
"Yes, this is a way to determine who is the Veteran's primary care physician. In case we need to contact/info the Veteran's primary care physician regardling their treatment, we need to know the proper physician to contact. 

So we need to have this field. I do not know if checking Yes or No actually dictate what shows below, since from our conversations it appears that individuals can have PCPs at VA and non-VA sites. This question will confirm which one is the principle one.

Email from Peter Hunt, 7/16/2015 10:31AM PT

**Comment by emilyville** [comment]
fixed in pr #245
