### ISSUE TITLE
Patient/SCID Info: OEF/OID or OND

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#150]
This is different in the current UI and in the spreadsheet. Spreadsheet says:

{OEF/OIF or OND} 
Check Box: Yes/No - no is default

UI has:
Theatre of Service: None, OEF/OIF, OND

**Comment by awong-dev** [comment]
This is correct as is.  LAtest spreadsheet is out-of-date.
