### ISSUE TITLE
Make datepicker Patient/SCID Info: SCI Center Date of Arrival

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#151]
Date picker MM/DD/YYYY

**Comment by awong-dev** [comment]
Make date picker.

**Comment by emilyville** [comment]
this is done!

**Comment by kathypham-gov** [comment]
@emilyville In chrome, it appears that this field is still a text field. 
Looking at 
https://whispering-dusk-4439-pr-268.herokuapp.com
https://whispering-dusk-4439-pr-285.herokuapp.com/
