### ISSUE TITLE
Add Patient/SCID Info: Eligiblity for SCID services based on

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#153]
Dropdown: SCI, MS, ALS, other (Free text)

**Comment by awong-dev** [comment]
This field is missing and has ramifications on what other data is collected.  Information in issue is based on spreadsheet from Peter.

**Comment by kathypham-gov** [comment]
From email with peter: "Yes, this is a very important field. It denotes the current disease/eligibility status of Veteran."

So from the spreadsheet, if it is NOT SCI, then the the ASIA information does not need to be filled out.
