### ISSUE TITLE
Add Patient/SCID Info: SCI Etiology

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#154]
Only needed if #153 = SCI 

Not sure if radio or checklist: 
1. Sports
2. Assault
3. Transport
4. Fall
5. Other traumatic cause
6. Non-traumatic spinal cord dysfunction
9. Unspecified or Unknown - *spreadsheet says 9, but looks like a typo"

**Comment by awong-dev** [comment]
Means...only display if SCI is select for dropdown in #153

**Comment by awong-dev** [comment]
field is missing.
