### ISSUE TITLE
Patient/SCID Info: Neurological Level of Injury (NLI)

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#159]
Only needed if #153 = SCI
Two drop down lists side-by-side
First List = C, T, L, S
Second List = C01-C08, T01-T12, L1-L5, S1-S4-5

**Comment by awong-dev** [comment]
This is part of ASIA.

**Comment by kathypham-gov** [comment]
Taken care of by #156
