### ISSUE TITLE
Patient/SCID Info: Zone of Partial Preservation

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#162]
Only needed if #160 = Complete
Four boxes with 2 drown lists for each
Same design and answer choices ad field # 27 - copied this directly from spreadsheet. I do not know what this mean.

**Comment by awong-dev** [comment]
Also part of ASIA form.

**Comment by kathypham-gov** [comment]
Taken care of by #156
