### ISSUE TITLE
Update with list: Patient/Psychosocial: Current Occupation

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#165]
List: 1. Working (competitive labor market, includes military), 2. Homemaker, 3. On-th-job training, 4. Sheltered workshop,5. Student, 6. Unemployed (may or may not be looking for work), 8. Other, unclassified (includes volunteer, disability or medical leave), 9. Unknown.

**Comment by awong-dev** [comment]
Needs to be drop-down.

**Comment by emilyville** [comment]
this is done!
