### ISSUE TITLE
Update the selection fields for: Patient/Residency and Caregiver: Residency type

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#166]
Drop down: 
01 Private residence
02 Hospital
03 Nursing home
04 Assisted living residence
05 Group living situation
06 Correctional institution
07 Hotel or motel
08 Homeless
09 Deceased
10 Other, unclassified
99 Unknown

**Comment by awong-dev** [comment]
Needs to be drop-down.

**Comment by awong-dev** [comment]
UI does not match _EITHER_ spreadsheet.

**Comment by kathypham-gov** [comment]
Agreed. Looks like this section needs to be updated to match current spreadsheet. Current spreadsheet  = excel. I will make an attempt to make sure current spreadsheet is in GitHub always. @awong-dev @emilyville

**Comment by emilyville** [comment]
yikes, still not updated! 

merging with issue #292

**Comment by awong-dev** [comment]
@kathytpham does this actually need to have the number "01 Private residence" in the name and not just "Private residence"?

**Comment by kathypham-gov** [comment]
Peter's list has the 01. Want me to clarify?

Sent with Good (www.good.com)

-----Original Message-----

**Comment by awong-dev** [comment]
Meh. I just put it in. I don't really care.
