### ISSUE TITLE
Add Patient/Residency and Caregiver: Type of Caregiver

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#167]
Radio:
{No Care Giver, Paid Family, Unpaid Family, Paid non-family, Unpaid non-family}

**Comment by awong-dev** [comment]
Needs to be drop-down.

**Comment by emilyville** [comment]
Merge with issue #292

**Comment by kathypham-gov** [comment]
Checked with the latest UI and saw that this is done with radiobuttons. Go @emilyville! Closing
