### ISSUE TITLE
Update field: Patient/Residency and Caregiver: Receiving Bowel/Bladder Non-VA Care

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#169]
Radio: Yes, No

**Comment by awong-dev** [comment]
Original spreadsheet asked "Are you receiving VA Care" and new one lists "are you receiving non-va Bower/bladder care."  These are very different concepts. Which do we want?

**Comment by kathypham-gov** [comment]
Confirmed with Peter:  Receiving Bowel/Bladder Non-VA Care

**Comment by awong-dev** [comment]
Reflected in UI. Closing
