### ISSUE TITLE
Find a prettier way to display/view episodes of care

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#17]
Having a straight up list is fine, but it'd be nice to have a visualization that would let you know how often these things were occurring.

This is a super low priority nice to have...probably only worth about ~1hour of work tops. If it takes more than that, we should drop it.

**Comment by Erik-Wallen** [comment]
I'm not a provider and I don't know exactly how they would want to use this but to me it would be valuable to see these scores over time.  One way to do that would be to put assessment scores in rows and episodes of care into columns and sub columns.

| Assessment | Episode of Care 1 (date) | Episode of Care 2 (date) | Other episodes of care (or times this assement was collected |
| --- | --- | --- | --- |
|  | Start   Goal   Finish | Start    Goal   Finish | Score |
| ---------------- | -------------------------------- | ---------------------------------- | ------------------------------------------------------------------------------------ |
| ASIA |  |  |  |

**Comment by huttj** [comment]
This sounds like a use case for reports.

I think it is important to know what sort of questions providers want answers to. We can answer any possible question that we have the data for, but each question is going to have an optimal layout that makes it easy to read and understand.

So, can we get a list of questions from actual providers such as:
- "How has a patient's ASIA score changed over time?"
- "How have all of a patient's measurements changed over time?"
- "Which patients are overdue for follow-ups?"
- "What is the average improvement of `measurement` over time for a patient at a given station?"

I just made those up, but the point is that we need to know what providers want to know.

**Comment by emilyville** [comment]
This is pretty old and no longer relevant.
