### ISSUE TITLE
Patient/Residency and Caregiver: Check if receiving HHH/A

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#172]
Checkbox: Yes, No

Note: For Yes and No, sometimes the spreadsheet uses radio and others check boxes. We should be consistent.

**Comment by awong-dev** [comment]
Field is missing.

**Comment by kathypham-gov** [comment]
Field exists. If is off the the side in the UI.

**Comment by emilyville** [comment]
this is done.
