### ISSUE TITLE
Annual Eval/Clinical: BMI -- do calculation.

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#177]
BMI needs calculation.
![image](https://cloud.githubusercontent.com/assets/10030313/9823471/4441304e-587b-11e5-8a94-4fab9be5ae81.png)

Annual Eval Tab: A8-A10

**Comment by awong-dev** [comment]
Done.

**Comment by awong-dev** [comment]
Should we be calculating for them?

**Comment by awong-dev** [comment]
FYI, SCI BMI uses different formula from standard BMI.

**Comment by awong-dev** [comment]
removing comment placing this with form fixes, and instead moving it to #290

**Comment by emilyville** [comment]
Since CPRS automatically calculates this, recommending only needing to add unit of measurement and helper text recommendation that they grab pre-calculated BMI

**Comment by emilyville** [comment]
I'm not sure where this landed so assigning back to Kathy - are we good as is or do we need more calculations? Currently looks like this:

![screen shot 2015-08-31 at 4 33 37 pm](https://cloud.githubusercontent.com/assets/1307774/9592980/12a92c88-4ffe-11e5-9e32-6adf51fe6f16.png)

**Comment by kathypham-gov** [comment]
Please update the label to "Computed BMI" The field can stay as is. Thanks!
