### ISSUE TITLE
Get list of critical data fields for each episode of care.

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#18]
@iamkevinscott There were enough e-mails flying between Phil and Peter that I lost track of what is the authoritative word on the data fields and instruments we need to implement.

I need a doc listing those fields. Then I can line it up with the data dictionary and implement.

**Comment by iamkevinscott** [comment]
@awong-dev 

## Registration

### Demographics

| Data Fields | Answer Choice | Note |
| --- | --- | --- |
| Last Name | Text box |  |
| First Name | Text box |  |
| Social Security Number | Text box |  |
| Date of Birth | Text box |  |
| Computed Age | Text box with formula |  |
| Gender | Check box |  |
| New Injury | Check box |  |
| OEF/OIF/OND | Check box |  |
| SCI Center Date of Arrival | Date field with calendar |  |
| Active Duty | Check box: yes/no |  |
| Assigned VAMC | Drop Down box with station # |  |
| Assigned HUB | Drop Down box with station # |  |
| Preferred HUB | Drop Down box with station # |  |
| Assigned SCI Coordinator | Drop Down box with names |  |
| PCP at Assigned HUB | Text box |  |
| PCP at Assigned VAMC | Text box |  |

### SCI/D Information

| Data Fields | Answer Choice | Note |
| --- | --- | --- |
| Type of SCI/D | Check box: SCI, MS, ALS, Other |  |
| MS subtype | Drop Down box |  |
| Date of onset | Date field with calendar |  |
| Level of Injury | Drop Down box |  |
| Asia Impairment Scale | Drop Down box |  |
| Complete/Incomplete | Check box |  |
| Traumatic/Non-traumatic | Check box |  |
| Etiology | Drop Down box |  |
| Date of AE Offered | Date field with calendar |  |
| Date of Last AE Received | Date field with calendar |  |
| Next AE due date | Date field with calendar |  |
| Date of Last Colonoscopy | Date field with calendar |  |
| Date of Last Sigmoidoscopy | Date field with calendar |  |
| Date of Last Diabetic Retinal Screening | Date field with calendar |  |
| Service Connected for SCI | Check box: yes/no |  |
| Date of Death | Date field with calendar |  |

**Comment by iamkevinscott** [comment]
@awong-dev 

## Annual Evaluation

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| Date of AE Offered | Date field with calendar | Same as Date AE Offered on Registration tab |  |
| Date of AE completed | Date field with calendar | Same as Date AE received on Registration tab |  |
| Date of next AE due | Date field with calendar | Same as Next AE due date on Registration tab |  |
| AE IN or Out patient | Check box |  |  |

### Standard Instruments

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| ASIA | SCI Classification | See attachment |  |
| AUDIT | Alcohol Use | See attachment |  |
| BMI | Body Mass Index | See attachment |  |
| CAGE | Alcohol Use | See attachment |  |
| CES-D | Depression | See attachment |  |
| CHART-SF | Participation | See attachment |  |
| CYH | Health Status | See attachment |  |
| DAST | Drug Use | See attachment |  |
| DUSOI | Comorbidities | See attachment |  |
| DUSOI-A | Comorbidities | See attachment |  |
| FAM | Functional Assessment | See attachment |  |
| FIM | Functional Independence | See attachment |  |
| KURTZKE EDSS | Multiple Sclerosis | See attachment |  |
| KURTZKE FSS | Multiple Sclerosis | See attachment |  |
| MNFM | Function Modifiers | See attachment |  |
| PRIME-MD | Depression | See attachment |  |
| PUSH | Pressure Ulcers | See attachment |  |
| SF-MPQ | Pain | See attachment |  |
| SF-8 | Health Status | See attachment |  |
| SWLS | Satisfaction with Life | See attachment |  |
| PUMT-KIT |  |  |  |

### SCI/D Information

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| Bladder drainage method | Drop Down box |  |  |
| Date Colonoscopy Received | Date field with calendar | Same as Date of Last Colonoscopy on Registration tab |  |
| Date Sigmoidoscopy Received | Date field with calendar | Same as Date of Last Sigmoidoscopy on Registration tab |  |
| Date of Diabetic Retinal Screening | Date field with calendar | Same as Date of Last Diabetic Retinal Screening on Registration tab |  |

**Comment by iamkevinscott** [comment]
@awong-dev 

## Acute Rehab

### START

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| Date of Admission | Date field with calendar |  |  |
| ASIA | SCI Classification | See attachment |  |
| FIM | Functional Independence | See attachment |  |
| SWLS | Satisfaction with Life | See attachment |  |
| KURTZKE EDSS | Multiple Sclerosis | See attachment |  |

### GOAL

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| FIM | Functional Independence | See attachment |  |

### FINISH

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| Date of Discharge | Date field with calendar |  |  |
| ASIA | SCI Classification | See attachment |  |
| FIM | Functional Independence | See attachment |  |
| KURTZKE EDSS | Multiple Sclerosis | See attachment |  |
| USPEQ | Veteran Experience | See attachment |  |
| Discharge Location | Drop Down box |  |  |

### FOLLOW UP - 90 Days

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| 90 Day Follow Up Date | Date field with calendar |  |  |
| FIM | Functional Independence | See attachment |  |
| SWLS | Satisfaction with Life | See attachment |  |
| CHART-SF | Participation | See attachment |  |
| SF-8 | Health Status | See attachment |  |

### FOLLOW UP - One Year

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| One year follow up date | Date field with calendar |  |  |
| FIM | Functional Independence | See attachment |  |
| SWLS | Satisfaction with Life | See attachment |  |
| CHART-SF | Participation | See attachment |  |
| SF-8 | Health Status | See attachment |  |

**Comment by iamkevinscott** [comment]
@awong-dev 

## OMR

### START

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| Date of Admission | Date field with calendar |  |  |
| ASIA | SCI Classification | See attachment |  |
| FIM | Functional Independence | See attachment |  |
| SWLS | Satisfaction with Life | See attachment |  |
| CHART-SF | Participation | See attachment |  |
| DUSOI | Comorbidities | See attachment |  |
| FAM | Functional Assessment | See attachment |  |
| SF-8 | Health Status | See attachment |  |

### GOAL

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| FIM | Functional Independence | See attachment |  |
| FAM | Functional Assessment | See attachment |  |

### FINISH

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| Date of Completion | Date field with calendar |  |  |
| ASIA | SCI Classification | See attachment |  |
| FIM | Functional Independence | See attachment |  |
| FAM | Functional Assessment | See attachment |  |
| SWLS | Satisfaction with Life | See attachment |  |
| CHART-SF | Participation | See attachment |  |
| SF-8 | Health Status | See attachment |  |
| USPEQ | Veteran Experience | See attachment |  |
| Discharge Location | Drop Down box |  |  |

### FOLLOW UP - 90 Days

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| 90 Day Follow Up Date | Date field with calendar |  |  |
| FIM | Functional Independence | See attachment |  |
| FAM | Functional Assessment | See attachment |  |
| SWLS | Satisfaction with Life | See attachment |  |
| CHART-SF | Participation | See attachment |  |
| SF-8 | Health Status | See attachment |  |
| Place of Residence | Discharge Location | Same as Discharge Location under Acute Rehab |  |

### FOLLOW UP - One Year

| Data Fields | Answer Choice | Note | Attachment |
| --- | --- | --- | --- |
| One year follow up date | Date field with calendar |  |  |
| FIM | Functional Independence | See attachment |  |
| FAM | Functional Assessment | See attachment |  |
| SWLS | Satisfaction with Life | See attachment |  |
| CHART-SF | Participation | See attachment |  |
| SF-8 | Health Status | See attachment |  |
| Place of Residence | Discharge Location | Same as Discharge Location under Acute Rehab |  |

**Comment by philullrich** [comment]
Both Follow Ups should contain field "Place of Residence" with same drop down as Discharge Location (under inpt rehab).

**Comment by iamkevinscott** [comment]
@awong-dev 

## Reports

| Name of Report | Data Description | Note |
| --- | --- | --- |
| Individual Veteran Report | Dates/Results of all AE, AR, OMR |  |
| Station Specific AE | #, % of AE in a given time period |  |
| VHA SCI AE | list of #, % of AE for each SCI Center in a given time period |  |
| Station Specific AR | #, % of AR in a given time period |  |
| VHA SCI AR | list of #, % of AR for each SCI Center in a given time period |  |
| Station Specific OMR | #, % of ORM in a given time period |  |
| VHA SCI OMR | list of #, % of OMR for each SCI Center in a given time period |  |
| New Injury per station | List of all new injuries in a given time period |  |
| Annual Report per station | Outcomes of AE, AR, and OMR station specific |  |

**Comment by iamkevinscott** [comment]
Thanks @philullrich for catching that.  @awong-dev please note above the comments that @philullrich made regarding OMR. 

> Both Follow Ups should contain field "Place of Residence" with same drop down as Discharge Location (under inpt rehab).

**Comment by awong-dev** [comment]
Nice catch @philullrich!  FYI, all of us can actually go edit each other's previous comments. I'll go fix.

**Comment by awong-dev** [comment]
@philullrich @pchunt 
Couple of questions:
    1. What does OMR stand for?  I had been calling things "outpatient episodes" but there seems to be a better name.
    2. Should "Place of Residence" also apply to both followups in Accute Rehab?
    3. How should the {START, GOAL, FINISH, FOLLOWUP-90, FOLLOWUP-1YR} set of categories look on the UI?

On (3), as an example, let's assume we're recording an Accute Rehab episode that started in Oct 20, 2014.  Let's say the patient was admitted for 3 days. That would be 1 accute rehab episode correct?  Would that include the {START, GOAL, FINISH} fields?  

Then we have a followup in Jan 25, 2015.  Is that considered a second episode of care where we just record the 90-day followup fields?  Or do we find the original Accute Rehab episode and annotate that?

**Comment by philullrich** [comment]
1. OMR = outpatient medical rehabilitation
2. Place of Residence should apply to both follow-ups.
3. Yes, start-goal-finish should be included in 1 acute rehab episode, but the follow-up data should also connected with the acute rehab episode.

**Comment by philullrich** [comment]
LOCOMOTOR MEASUREMENT.  Not sure how to submit this as nice tables as Kevin did.  The following fields are used among veterans with SCI/D that walk, when they come in for annual evaluations, or if they complete inpt rehab with some walking ability.  So, we might simply include these on the annual eval list above, and as part of the Start and Finish acute rehab measures.  That would address the current uses by physical therapists in our system.  I looked for way to add these by editing prior notes but sorry could not see how to do that.  

Field   Type
Site    string
Fis Yr  date
Last Name   string
SSN integer
Date of Assessment  date
Setting multiple-choice (aka dropdown)
If Inpatient Rehabilitation, Start or Finish    multiple-choice (aka dropdown)
No. of Falls in previous month  integer
No. of Falls in previous 6 months   integer
No. of Falls in previous 12 months  integer
Dynamic Gait Index (8 items)    integer
Timed up and Go integer
SCI-FAI (33 items)  integer
Reach   integer

**Comment by pchunt** [comment]
Thanks Phil. Yes, I am aware of the Locomotor measurements and have seen and used the spreadsheet. For now, we will treat this the same way as other survey instruments in the SCIDO. We are simply using a data field labels as “locomotor measurements” as a place holder. Until we determine the final list of data fields/instruments to be included in the final version of this interim SCIDO database, then we will flesh out all the answers, algorithms, and data fields for each of these instruments. Please be advised that we are not trying to replicate the current SCIDO system. We would like this interim SCIDO database to be a very simple and stripped down database to collect the minimum SCIDO dataset.  I believe Albert will have the initial version of this interim system to show the team next week. I will coordinate a meeting for the team to view the demonstration. Phil, you are included as a member of this review team. More info to come, please stay tuned….

**Comment by philullrich** [comment]
Maybe we're on the same page, Im not sure.  My insistence on including the locomotor measures is expressed with a minimum system in mind ..... it has nothing to do with replicating SCIDO.  Currently the locomotor data has the same 'mandatory' collection status as the other spreadsheet data.  If this placeholder sets things up to assure that these measures remain under consideration then I am satisfied.

**Comment by awong-dev** [comment]
@philullrich I'll can show you how to do Markdown next time I'm in the Fort Lawton office. For now, create a new issue for Instruments and moving your description there. Would like to keep this issue focused on just the initial stab at the shell data fields.  See #32

**Comment by awong-dev** [comment]
I'm going to close this issue. Kevin copied Peter's spreadsheet here which is a good enough initial stab.

If there are updates/additions/changes, create a new issue instead of responding to this one.
