### ISSUE TITLE
Create fundamental User Journeys

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#19]
These should just be rough first stabs scoping the domain of users. (how many types? 2-3 sentences describing them. What're the critical few tasks they do.)

**Comment by awong-dev** [comment]
This task is too large next step to break down into smaller tasks and then execute. Possibly assign some to peter.

**Comment by iamkevinscott** [comment]
Breaking these up into smaller pieces to accomplish and assigning them to others on the team.
