### ISSUE TITLE
Update options for Acute Rehab/Info: Reason for Admission

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#190]
Radio: Newly injured, Deconditioned, Transition to home, Other (free text field)

Add conditional text if "Other" is selected.

**Comment by kathypham-gov** [comment]
This one is done.

**Comment by kathypham-gov** [comment]
Add a conditional text if "Other" is selected.

**Comment by awong-dev** [comment]
part of #292

**Comment by awong-dev** [comment]
Fixed by @emilyville in 155cf6e
