### ISSUE TITLE
Make datepicker:  Acute Rehab/Info: Date of Acute Rehab Admission

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#192]
Datepicker

Current UI says "Acute rehab admission." Update to say "Date of Acute Rehab Admission"

**Comment by emilyville** [comment]
I put "date" at the end for each of these so it's consistent. 

![screen shot 2015-07-17 at 3 31 34 pm](https://cloud.githubusercontent.com/assets/1307774/8758425/f722cab0-2c98-11e5-8a6d-c600d7ade03f.png)

**Comment by kathypham-gov** [comment]
Date picker does not appear fixed.
