### ISSUE TITLE
Create Acute Rehab/Start Section

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#198]
The following Items need to be in the Acute Rehab/Start section:

1) ASIA Widget from #212
2) FIM Widget from #202 
3) SWLS Widget from #200 
4) SF-8  Widget from #201

**Comment by awong-dev** [comment]
part of #287

**Comment by awong-dev** [comment]
Implementing the widgets will solve this. This is not interesting as a separate issue.
