### ISSUE TITLE
Set up Deploy to Heroku

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#2]

**Comment by awong-dev** [comment]
I don't have VA server access yet, so starting with just EC-2

**Comment by awong-dev** [comment]
The critical thing here is to get something up for the clinical team to look at. EC-2 didn't quite work due to VA firewalls, but Heroku supposedly isn't blocked. I've deployed there.

https://whispering-dusk-4439.herokuapp.com

**Comment by awong-dev** [comment]
@iamkevinscott given that you filed #100, am I right to believe that the herkouapp.com link worked from within the VA network?

**Comment by iamkevinscott** [comment]
You are correct sir!

**Comment by awong-dev** [comment]
Aweeeeesome.  Closing.
