### ISSUE TITLE
Gather input from MIO coordinators

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#20]
Hey @iamkevinscott, can you work with Belinda to get this going?

Also, if she's willing to create an account, we could just assign tasks to her here.

**Comment by belindaf** [comment]
MIO C comments or questions re interim system April 2015

 With the interim system

• I’ve been updating my patient list regularly. Are we carrying forward the important information like Registration Status, SCI Network and  VHA Handbook 1176 items to the interim system?
• Will I be able to get a patient list of patients who have been seen at our SCI Center? Past and currently?  
• Will the interim system still be set up as a Hub and Spokes system, and will I be able to get a list of patients who are registered in our SCIDO Data region? 
• I would like the interim system to have the EDSS measure for our Veterans with MS.
• I have been asked for a list of patients with MS whom we treat. Right now I use etiology and Registration Status to determine which patients are MS without SCI/D.   Do I put patients who have MS and no SCI/D into the Interim System?
• I would like to be able to get a list of patients who have ALS from the Interim system.  PVA asked for our method for tracking patients with ALs. Right now we use etiology code (Motor Neuron Disease) and Registration Status (usually NS = Not-SCD, and SCI Network fields.   Do we still put patients who have ALS into the Interim System?  
• Another MIO asked for a special code or a new system to designate ALS patients. Could you add something to the interim and new system?
• Will SCI Coordinators have access to the interim system? Will SCI Coordinators be able to get their own list of patients or do MIOs have to supply that to them?  
• Will the interim system include a place to enter the core assessments (e.g., FIM, ASIA, CHART-SF, CYH, SWLS, SF-8)?  
• Will MIO Coordinator have to type in Veteran information that now comes from VistA (which is updated every night from a nightly demographic update between VistA and SCIDO), such as patient address, telephone number, enrollment priority, etc?
• I would like the PUMT (pressure ulcer monitoring tool) 
• Will annual evaluation assessments currently collected going to be included with the interim program such as Care Type, score type, instrument name, record date, EDSS?  

Things requested that are updated or available through VistA
• I would like to be able to print address labels for our facilities patient population. (Note: SCIDO saves the address information, so we would have the latest address information right after SCIDO is cut-off, but we would not have the address updated obviously without a VistA connection).
•  I would like contact information, address, telephone, gender.  
• Can we please add age, race, ethnicity, gender, and state to the list? From time to time, I am asked for this information from our stakeholders. For example, Members from the Advisory Committee for Minority Veterans were recently here and asked about the race and ethnicity of the SCI population served;

**Comment by belindaf** [comment]
I pasted in input in the comments of #20 and the system appears to have closed it.

**Comment by awong-dev** [comment]
@belindaf Did you want to reopen?

Also, FYI, you might want to remove your signature when responding to github e-mails. It ends up in the comments (though I just deleted the sig for you just now)...

**Comment by belindaf** [comment]
Thanks for the tip re signature.

I’m not up to speed with how this system is used.  I don’t know whether it should be closed or not to meet the needs of those using it.    

If the info in the comment is enough for this assignment and you can get the info from this assignment, then perhaps it should stay closed. Let me know what you think.

Thanks again.

Belinda

**Comment by awong-dev** [comment]
I'm reopening and assigning to Kevin. @iamkevinscott can you look over Belinda's input and see if you think it's complete enough for us to move forward?

**Comment by Erik-Wallen** [comment]
@awong-dev  @iamkevinscott  fyi, there's an existing registry of MS patients that managed by another VA Office - the MS Centers for Excellence.  We may want to connect with them.

**Comment by iamkevinscott** [comment]
@awong-dev This is a good start and consider this complete.  We can open another issue and refer to #20
