### ISSUE TITLE
SCI/D application problem document

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#21]
Write a 1-2 page outline of the SCIDO problem and how they are going to approach it, which is to have Albert work closely with the SCIDO team to understand their needs, try out some different prototypes and tests, etc. until arriving at a proposed solution we would like to move forward with. This outline is not PMAS Increment 0. 

At the conclusion of the prototype/research phase, we will get back together to discuss whether the proposed way forward fits PMAS criteria or if there is another way forward that still lets OIT have a documented record of the project in order to be able to support it in the future.

**Comment by iamkevinscott** [comment]
Completed first draft for review.

**Comment by iamkevinscott** [comment]
Dr. Chun has reviewed the document and provided additional changes and feedback to the document.  This should be sufficient enough to close out and send to key stakeholders, Aaron Drew and Marina Martin.

**Comment by awong-dev** [comment]
Is the main sent? I didn't see it in my inbox. Happy to not be CCed...but if it's not sent, would like to be CCed :)
