### ISSUE TITLE
Instrument: Implement Standard FIM Widget and use in all pages

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#213]

**Comment by awong-dev** [comment]
part of #287

**Comment by emilyville** [comment]
like so. 
![screen shot 2015-08-12 at 4 18 43 pm](https://cloud.githubusercontent.com/assets/1307774/9239172/0ff4b934-410e-11e5-8e85-d0624f47ac9c.png)

**Comment by awong-dev** [comment]
Fixed!
