### ISSUE TITLE
Get everyone on Github

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#22]

**Comment by iamkevinscott** [comment]
@Erik-Wallen and @pchunt added to the SCIIRepository

**Comment by iamkevinscott** [comment]
@awong-dev please add philullrich and belindaf to the Repository

**Comment by awong-dev** [comment]
@iamkevinscott Done.

**Comment by iamkevinscott** [comment]
Waiting for Dr. Chun and Susy George to create and send me their usernames.
Sent 2nd email request today.

**Comment by iamkevinscott** [comment]
@awong-dev please add Vhalongeorgs (Susy George) to the repository

**Comment by awong-dev** [comment]
@iamkevinscott Sounds like there are still problems with that username. I cannot find it to add.  I saw an e-mail saying you couldn't find the user...did you confirm with Susy that it's the right username?

**Comment by pchunt** [comment]
Hi Albert and Kevin,

I think Susy misunderstood your request. I believe she gave you her NT account ID. Based on my experience, it’s a bit of challenge to figure out how to register and create an account on GITHUB. Why don’t we hold off this for now and have Albert do a demonstration on how to register and use GITHUB next week before he does the interim SCIDO demonstration?

To be honest with you, so far I haven’t found any significant advantage of using GITHUB as a communication/project management tool over using group email. Perhaps I am wrong. Albert, could you help  educate us a little more about the advantages and usage of GITHUB when you do the demonstration next week?

Thank you both.

**Comment by awong-dev** [comment]
@pchunt Are you only interacting with github via e-mail? If so, then you won't see much difference...in fact it's probably a little worse than group e-mail.

For me, it's been majorly useful this week. I know that we're only 40% of the way through our work commitments this week. I can directly reference information from you in my source code. And it's clear who owns which task.

I can show a demo next week.

**Comment by pchunt** [comment]
Great. Thanks Albert!!!

**Comment by iamkevinscott** [comment]
@awong-dev please add @vhalonchuns to the repository.

**Comment by iamkevinscott** [comment]
@pchunt I am assigning this last part to you.  Please assist Susy George in creating a Github account and providing that to @awong-dev and myself.  Thanks!

**Comment by iamkevinscott** [comment]
Closing this out and creating a new issue for m3 and referring #22  This work is 95% done.
