### ISSUE TITLE
Implement shared ASIA widget mockup

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#228]
Put in `app/views/shared/_asia_widget.slim.html` or something similar.  The directory location and the leading underscore matter to rails.

This is the frontend side of #212

**Comment by emilyville** [comment]
Working off of this mockup
![screen shot 2015-07-16 at 2 06 49 pm](https://cloud.githubusercontent.com/assets/1307774/8735625/2a5252a2-2bc7-11e5-8f26-c405d4d70136.png)

**Comment by awong-dev** [comment]
I think is is correct (or at least correct enough)...but don't put the date or paging stuff in the widget.  We need to embed this in places w/o dates.

**Comment by emilyville** [comment]
close with pr #243
