### ISSUE TITLE
Add OMR/Start Section

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#232]
This start section needs the following: 
Date of Admission: Date picker
Change in ASIA or NLI: Yes or No
Asia Instrument from #212 
SWLS #214 
CHART-SF #216 
SF-8 #215 
DUSOI #236 
Care Tool #235

**Comment by kathypham-gov** [comment]
@awong-dev @emilyville Have either of you heard of the DUSOI or Caretool instrument before? Is this new? May be worth pulling DUSOI and Caretool out of this list and add to a different issue if these are new or not priority.

**Comment by awong-dev** [comment]
part of #292

**Comment by emilyville** [comment]
merged with issue #339. Closing.
