### ISSUE TITLE
Add OMR/Finish Section

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#234]
This section has:
Date of Completion: datepicker
Discharge Location

ASIA #212 
SWLS #214 
Chart-SF #216 
SF-8 #215 

I think the following are new (kathy):
Caretool #235 
USPEQ #237 
Locomotor #238

**Comment by philullrich** [comment]
A note about uSPEQ.  This is a patient satisfaction survey primarily governed by a contract between a VA data quality office (not us) and the organization called CARF.  Bottom line, heads up we wont/cant collect the data ourselves.....

**Comment by awong-dev** [comment]
part of #292

**Comment by emilyville** [comment]
merged with issue #339. Closing.
