### ISSUE TITLE
Instrument: Implement Standard DUSOI Widget and use in all pages 

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#236]
Currently used in:
OMR

**Comment by emilyville** [comment]
Assigning to Kathy since we're not doing this one. Should we keep the form input for the calculated DUSOI (assuming that's a thing?) 

https://www.youtube.com/watch?v=LJP1DphOWPs

**Comment by awong-dev** [comment]
not doing.
