### ISSUE TITLE
Upload spreadsheets of SCIDO data fields

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#24]
Get SCIDO data fields from Peter and upload them to the project site.

**Comment by iamkevinscott** [comment]
@awong-dev Uploaded these data sheets under another entry.  Is there a way to connect these two?

**Comment by awong-dev** [comment]
I would just write a note reference the other issue, and close this one...like follows.

@iamkevinscott added the entries under #18. Closing this as a dupe.

(There's also a duplicate label that we can add for stuff like this)
