### ISSUE TITLE
Add OMR/Followup 1 year section

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#240]
This section has:
One year Follow Up Date: Datepicker
Caretool #235 
SWLS #200 
Chart-SF #216 
SF-8 #201

**Comment by awong-dev** [comment]
Part of #292

**Comment by emilyville** [comment]
I was really confused by this issue and almost everything is references is closed, so I looked at the spreadsheet and it seems like we have the all of the instruments, but they need to be repeated in the follow up 90 days, and follow up 1 year. (Neither of these exist at all on OMR currently)

Attaching a screenshot of the spreadsheet (!!) for reference.

![screen shot 2015-08-31 at 10 35 44 am](https://cloud.githubusercontent.com/assets/1307774/9585530/6d253116-4fcc-11e5-9dbc-1bb3373988d0.png)

**Comment by emilyville** [comment]
merged with issue #339. Closing.
