### ISSUE TITLE
Add Report: List of All Patients

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#241]
Related to #94 CSV Exports for reports

**Comment by emilyville** [comment]
For now...

First Name, Last Name 
SSN
station

@awong-dev I think you mentioned a date but not sure which date you are referring to.

**Comment by awong-dev** [comment]
Right. date doesn't make sense. ignore me.

**Comment by ShawnArnwine** [comment]
@emilyville will users need to search by SCIDO Patient ID?

**Comment by emilyville** [comment]
@ShawnArnwine I don't think we need search anymore at all. I think everything that is currently there we don't need anymore. Let me know if you want to chat more about this since it's 1st on my priority list today as well.

**Comment by awong-dev** [comment]
Part of #288

**Comment by awong-dev** [comment]
fixed in #268 .
