### ISSUE TITLE
Make it so Name is optional in the address form partial

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#242]

**Comment by emilyville** [comment]
connected with issue #253 and issue number #252

**Comment by emilyville** [comment]
And let's remove name completely.

**Comment by awong-dev** [comment]
part of #292

@emilyville Is this done?

**Comment by emilyville** [comment]
is removed. There may be an issue opened for adding caregiver name, but it will be reflected in MIO coordinator feedback. closing for now.
