### ISSUE TITLE
Follow up on eHMP EC-2 instance access.

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#26]

**Comment by awong-dev** [comment]
@iamkevinscott Do you have Betsy Green's e-mail? If need to ask her for eHMP access.

**Comment by iamkevinscott** [comment]
@awong-dev  yes, Elizabeth Green 4 at va.gov

**Comment by awong-dev** [comment]
Got access for all of the DS VA team.  Apparently there isn't actually any ec-2 access. Main access is to github, nexus repository, and the project wiki.
