### ISSUE TITLE
Add Classification of SCI Injury to ASIA form 

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#260]
Need to add Classification of SCI Injury to ASIA Form: High Tetra (C1-C4, A,B,C), Low Tetra (C5-C8, A,B,C), Para (A,B,C), ASIA D (at Start)

Right now it is a field separate from the ASIA Widget

**Comment by emilyville** [comment]
merging with issue #292

**Comment by awong-dev** [comment]
@emilyville I had to undo your fix. Let's chat monday.

**Comment by awong-dev** [comment]
Reassigning to Kathy. This seeps to be a repeat of what was listed in your uber issue.

There is confusion from our side about why this should be in the asia form proper...or if it is, whether it's a classification that's set per Asia evaluation, or a global status for the patient.

**Comment by emilyville** [comment]
I think this was addressed with closing of issue #381
