### ISSUE TITLE
General Updates to Update Acute Rehab Page

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#262]
1) Move hospital discharge date, acute rehab discharge date, residence type to "Discharge section"
2) Change reason of admission to radio button
3) Remove residence name 
4) Start section should only have ASIA form, Replace the three text boxes with the actual instruments
5) Goal section should only have FIM instrument
6) Finish Section should have Asia form, Replace the three text boxes with the actual instruments
7) Followup 90 day section - replace instrument text boxes with actual instruments
8) followup 1 year - replace instrument text boxes with actual instruments

**Comment by emilyville** [comment]
merging with issue #292

**Comment by emilyville** [comment]
X Move hospital discharge date, acute rehab discharge date, residence type to "Discharge section"
X Change reason of admission to radio button
X Remove residence name 
X Start section should only have ASIA form, Replace the three text boxes with the actual instruments
X Goal section should only have FIM instrument
X Finish Section should have Asia form, Replace the three text boxes with the actual instruments

Adding the other instruments in this page will be covered with issue #287 

Migration: Removed residence name
