### ISSUE TITLE
Contact Power Users for Alpha Phase

### ISSUE THREAD

**Issue by kathypham-gov** [department-of-veterans-affairs/SCIInterim#270]
Monique Washington - CLeveland
Angela Gonzalez - Houston
Theresa Freeman - Memphis
Younghee Kang - Tampa

**Comment by kathypham-gov** [comment]
Tested with Angela, Alicia, and Fatima. Kathy to reach out to Monqiue, Theresa, Younghee.

**Comment by awong-dev** [comment]
Is this still a valid issue? What's needed to close?

**Comment by kathypham-gov** [comment]
Done. Talked to Angela (Houston), Alicia (Palo Alto), and Fatima.
