### ISSUE TITLE
Fields that aren't being saved

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/SCIInterim#274]
from patient edit/new:
assigned VAMC, and all facilities locations (edited)
non VA facility - ALL
SCI Eligibility
ETIOLOGY 
complete/incomplete in ASIA
caregiver radio
ALL states in addresses (state as in Texas)
SCI Other
SCI Arrival date
benefit waiver exception date

annual eval lost most allthethings

additionally, 
looks like some fields are lost when we navigate away from the patient and then back, which is confuse-surprising.

**Comment by emilyville** [comment]
Fixed 
annual eval lost most allthethings
benefit waiver exception date
SCI Arrival date
SCI Other
assigned VAMC, and all facilities locations (edited)
SCI Eligibility
ETIOLOGY

PUNT
annual eval, is_inpatient
caregiver radio - this needs to be migrated from a boolean to integer
ALL states in addresses (state as in Texas)
complete/incomplete in ASIA

looks like some fields are lost when we navigate away from the patient and then back, which is confuse-surprising.

**Comment by awong-dev** [comment]
Fixed caregiver radio in #272

**Comment by emilyville** [comment]
Removing states since it needs to be a dropdown. 

still remaining:
annual eval is_inpatient
complete/incomplete in ASIA
