### ISSUE TITLE
Datepicker, datepicker datepicker

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/SCIInterim#275]
known issues regarding datepickers:

not reliable between browsers
reliably never works in IE
HTML5 datepicker doesn't work in Firefox. 
date doesn't display consistently w/ dd/mm/yyyy or yyyy-dd-mm etc

The following fields need to be datepickers:
#151
#171
#173
#174
#175
#191
#192
#193
#194
#195

**Comment by kathypham-gov** [comment]
Added updating datepickers for specific fields: The following fields need to be datepickers:
#151 
#171 
#173 
#174 
#175 
#191 
#192 
#193 
#194 
#195 
Also, this is a meta issue.

**Comment by awong-dev** [comment]
We need html5 on supported browsers with javascript fallback, probably using jquery-ui datepicker.  See this:

http://www.sitepoint.com/finding-date-picker-input-solution-bootstrap/

**Comment by awong-dev** [comment]
All fields fixed. Now we just need to handle javascript fallback. Creating separate issue.
