### ISSUE TITLE
"Receiving bowel/bladder non VA care" on patient registration...is that a bad label?

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#279]
The underlying variable is "is_receiving_non_va_care"

**Comment by emilyville** [comment]
There are a lot of issues with this label / and the MIOs still found it to be unclear. 

merging with issue #290

**Comment by kathypham-gov** [comment]
The purpose of this field: Know if the patient is receiving Bowel and Bladder Care. According to Alicia, a patient may need bowel/bladder care (help going to the bathroom) when they are discharged. So this is usually implied non-VA care. We need a better name for this.

**Comment by kathypham-gov** [comment]
Engineering effort: 1 for updating the name of the field
Non-engineering effort: 2 for coming up with a new name with clinical team.

**Comment by emilyville** [comment]
@kathytpham I think we decided to keep this label despite it being confusing? shall I close?

**Comment by kathypham-gov** [comment]
According the new spreadsheet, this should now say: "Is the Veteran receiving Bowel/Bladder Non-VA care?" Which is not much clearer. @emilyville

**Comment by awong-dev** [comment]
Can we make a decision on the action here?  If we think the wording is unclear, then let's pick a clear wording, make the UI change, and close the issue.

We _know_ the clinical team's opinion is not correct in terms of making an understandable product so let's attempt to "do the right thing" to be the best of our ability and then present to them to iterate.

**Comment by awong-dev** [comment]
assigning to @kathytpham to wordsmith.

**Comment by kathypham-gov** [comment]
@awong-dev I've looked at it enough that at this point, it makes sense to me. They need to know if the Vet is getting Bowel/Bladder care when they get discharged from the VA. Keep it.

**Comment by kathypham-gov** [comment]
Peter confirmed that this label should remain as is.
