### ISSUE TITLE
Fix DB type for field has_caregiver

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#281]
patient_has_caregiver is now being used as a select, but the nameing and the database type are boolean.

Please rename and add migration to make the thing an integer, not a boolean.

As is, I'm actually really not certain why the server ever lets you save the form....

**Comment by emilyville** [comment]
merging with issue #292

**Comment by awong-dev** [comment]
Not sure why this didn't close. But is fixed by 0239ad1
