### ISSUE TITLE
Basic functionality in all major forms complete

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#292]
That's Patient Registration, Annual Eval, Acute Rehab, OMR.
### Make it consistent with the spreadsheets (all small things)
- #171 
- #260
- #261
- #261
- #293
### Broken things
- #231 
- #280 
- #281 
### UI <3
- #211
- #258 
- #277
- #266
- #292
- #167
### Instruments AE
- #173
- #174
- #175
- #190
- #194 
- #195 
- #196
- #197 
- #205 
- #206
### Instruments OMR
- #339
### Instruments ASIA
- #255 
### Address stuff, blocked on not having location lists
- #259
- #142
- #147
- #148
- #166

**Comment by emilyville** [comment]
Closing this - I believe all remaining ones are blocked or unclear.
