### ISSUE TITLE
Ensure all data fields int he episodes of care have the correct format and data type.

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#30]
Ensure they have the correct data type (date, integer, string, boolean, etc). This allows for simple validations and unittests.

**Comment by awong-dev** [comment]
Per discussion on the phone, all I'm trying to do is some extremely minimal validation.

For reference, SQL databases knows some very basic types:
1. string
2. integer
3. date
4. boolean
5. multiple-choice (aka dropdown)

Knowing this type affects more than just the UI. I just want to know, per field, which of those categories it falls into. I think I can can look at the data dictionary to find that info without much trouble. But I promise not to spend much time on it or add additional fields.

**Comment by pchunt** [comment]
Those options will suffice. Thanks Albert!

**Comment by awong-dev** [comment]
@pchunt Sorry I wasn't clear...I need to know, per field, if they are a string, integer, date, boolean, or multiple choice.  Otherwise the UI behaves in a funky manner.

We can cover this next week.

**Comment by pchunt** [comment]
Morning Albert,

For now, just make all of them a string. As the review team goes through each of the data field, we will determine whether or not to keep the data field and what kind of answer choice/format each data field will take on. This may be very different from the current SCIDO dictionary. For the demonstration, as you go through the data field, please have the SCIDO dictionary in the background, so the team can use it to cross reference the discussion.

**Comment by huttj** [comment]
Beyond just the type of each field, for fields that aren't multiple choice, it is important to know if the field has a specific format. For example, SSNs are numeric and only nine digits long, but there is [an additional set of constraints](http://stackoverflow.com/questions/1517026/how-can-i-validate-us-social-security-number) involved in checking to see if a given number is valid or not. Having those in place can be very effective in preventing easily avoidable errors during data entry.

For common things like SSNs, the validation isn't too difficult to figure out. However, for less common medical measurements, there may ranges, formats, or other subtleties that define which values are valid, and those are very important to have available. Similarly, certain values may influence the validation of other values.

**Comment by philullrich** [comment]
If it would be helpful, I and/or Belinda can take on the task of labeling fields with data types.

**Comment by belindaf** [comment]
Yes, I’d be happy to help in any way.

There is also the main SCIDO data listings, which lists all the fields, the datatypes, length, etc.   It is a word document I emailed to Albert.   (I think it would be easier to use in Excel.)

I believe most of these datatypes will be the same.  Would you see if the datatype and fields there are what you’re looking for?

**Comment by pchunt** [comment]
Morning Phil,

Yes, you and Belinda are among the review team members. Together the team will decide on which data fields to be included in the interim SCIDO system and how each data field will be labeled, defined, and formatted.

Thanks.

**Comment by pchunt** [comment]
Thanks Belinda. Just FYI: we are not interested in replicating the current SCIDO application. We just want to build a stripped down model to collect the minimum required data set to be implemented ASAP. Having the current SCIDO dictionary as reference would be very help. Your input during the review will be invaluable. Thanks!

**Comment by awong-dev** [comment]
@pchunt We're spending more time discussing whether or not I should get the data field types from SCIDO than it'd take for me to get the SCIDO types and implement them.

Not having something in this info is making it harder for @huttj to understand the UI flow.

Let me take reigns on this task for now. If the review board decides to prune or change it later, we can do it then, but absent more requirements, I want to replicate this piece of SCIDO. Don't worry, this is neither a time sink or a defocusing from the end goal of getting a demo to the review board.

@belindaf and @philullrich will bug you in person.

**Comment by pchunt** [comment]
Hi Albert and Kevin,

I just scheduled the demonstration meeting for this Wednesday 3:00PM-4:30PM. Since all the folks on the review team are from the VA. To make it easy, Albert, could you do the demonstration in the Seattle Office? Can you work with Kevin to test to see if you can present via LYNC prior to the scheduled date and let me know?

Thanks Kevin and Albert!

Peter Cody Hunt, PhD, MPH
Rehabilitation Scientist
Spinal Cord Injury/Disorders Health Care Group
VA Long Beach Healthcare System (07/128)
5901 East 7th Street
Bldg 150, Room R104B
Long Beach, CA 90822
Phone: (562) 826-8000 ext. 6113
Fax: (562) 826-5718
Pager: (562) 683-1590
Email: peter.hunt3@va.govmailto:peter.hunt3@va.gov

**Comment by pchunt** [comment]
Peter,

I am on annual leave starting Wednesday.  Adding Erik Wallen who is assisting with this in my absence.
