### ISSUE TITLE
Score_Type and Care_Type needed for each assessment

### ISSUE THREAD

**Issue by craigjh** [department-of-veterans-affairs/SCIInterim#343]
Do we need to support Score_Type and Care_Type? These two fields are currently part of each assessment. Score_Type tells where in the patient care cycle the assessment was done (start, finish, 90-day, etc.) Care_Type indicates the care setting (inpatient rehab, annual evaluation, etc.)

**Comment by kathypham-gov** [comment]
Care_Type: We have Annual Eval, Acute Rehab, OMR. Albert confirmed that each Episode of Care has a way to link to the assessment 

Score_Type: We have start/finish/90 day, etc. THere is a way to link an Episode of care to its equalivalent start/finish/interim assessment. 

@awong-dev @craigjh
