### ISSUE TITLE
Need to choose URL for interim solution so the SSL cert can be requested

### ISSUE THREAD

**Issue by craigjh** [department-of-veterans-affairs/SCIInterim#366]

**Comment by awong-dev** [comment]
@alex What was the norm for your other systems?

I just expected the cert to be the Fully Qualified Domain Name of the server.

**Comment by alex** [comment]
@awong-dev Yup, for efolder-express and caseflow, we just used the FQDN of the servers, which makes me sad.

You can see https://github.com/department-of-veterans-affairs/deployment/blob/master/playbooks/tls/generate_csr.py, which was used to generate the CSR we sent them.

**Comment by awong-dev** [comment]
done. sticking with FQDN of server.
