### ISSUE TITLE
Create Fundamental User Journey - MIO Coordinators

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#41]
@philullrich @belindaf 
“User Journeys” are part of the requirements gathering for application development.  These should just be rough first stabs scoping the domain of users (MIO Coordinators). 
- 2-3 sentences describing them
- What are the critical few tasks they are trying to achieve
- What answers are they trying to get from the application to do their jobs

**Comment by belindaf** [comment]
MIO Coordinator User’s  Journey (belindaf 5/27/2015)

The MIO Coordinator
• will produce patient list(s) for their patients with SCI/D, including information such as etiology, neurological classification of injury (High Tetraplegia, Low Tetraplegia, Paraplegia, Paraplegia, ASIA D), Primary Care VAMC, Annual Evaluation VAMC, Last AE Received Date, Registration Status, SCI-Network, and demographic information.
• will add new patients with SCI/D to the SCI/D registry
• will want to be able to view and create SCI/D measures  that have been documented for Veterans with SCI/D
• will want to know which patients have received an Annual Evaluation during any fiscal period (quarter or annual)
• will want to track patients receiving inpatient rehabilitation and make sure that the core outcome measures are being completed for these patients at the appropriate time.
• Will produce list(s) of patients who do not have an SCI/D,  and have MS or ALS.

**Comment by awong-dev** [comment]
Closing all non dev-team related issues since they aren't being tracked by github anymore.
