### ISSUE TITLE
Create Fundamental User Journey - Physicians

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#43]
@vhalonchuns
“User Journeys” are part of the requirements gathering for application development. These should just be rough first stabs scoping the domain of users (Physicians). 
- 2-3 sentences describing them
- What are the critical few tasks they are trying to achieve
- What answers are they trying to get from the application to do their jobs

**Comment by vhalonchuns** [comment]
Copying Susy.

**Comment by awong-dev** [comment]
Closing all non dev-team related issues since they aren't being tracked by github anymore.
