### ISSUE TITLE
Remove show/delete handlers

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#47]
The ruby scaffold created a bunch of view for just show and handlers for delete. In our system, everything should always be in "edit" mode, so we should whack all of these out of the main controllers.

Should be easy to do. Just is a LOT of deletes.

**Comment by MrJadaml** [comment]
I've made a PR to remove those handlers/actions though that has led to a few questions. We have index pages for these different reports. Without knowing the system my guess is that there will potentially be multiple reports for each category of report? Currently on the index page each report is put in a table that then just generates a link to edit that report. This will result in a list of edit links w/out anything to show which report it will be linking to. Do we want to fill out that table so all the fields of that report show?

**Comment by awong-dev** [comment]
Fixed by pr #49
