### ISSUE TITLE
Extract common patterns out of Episode Of Care views/controllers

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#48]
There are too many repeated patterns and view templates in the code.

At the very least, create a nested layout. Possibly also extract some common functionality out of the controllers.

**Comment by MrJadaml** [comment]
What are the repeated patterns you're seeing in the views?

**Comment by awong-dev** [comment]
The simple_form_for blocks have a huge amount of wrapper boilerplate for
example.

Also, I imagine the patient_nav should be left_nav on all views...

**Comment by awong-dev** [comment]
Thanks! Will look in a bit. FYI, joshua and I are probably gonna hack
together on this for a bit today down in Ballard if you wanted to colocate.
Grabbing lunch now but will be online in maybe an hour...

As for delete, i think the right approach is to add an admin user. Its far
more dangerous to lose records than it is to have invalid ones.

**Comment by MrJadaml** [comment]
When and where? I may be able to join ya guys.

**Comment by awong-dev** [comment]
FYI, responded via email.

**Comment by awong-dev** [comment]
Stale bug. Already created a number of partials to reuse bits.
