### ISSUE TITLE
Clean up routes!

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#53]
(a) Don't have all the RESTful routes when we only want create/edit
(b) Don't have non-nested routes for episodes of care when they only make sense in the context of a patient.

**Comment by huttj** [comment]
If you're using the resource option, doesn't it create all of those route types for you? Should we go in and remove the extraneous ones by hand?

**Comment by awong-dev** [comment]
Right...I miswrote the first comment. Fixed. We don't want delete always exposed. Though I guess we can leave the routing table with resources to support all operations..esp for admin...and do a devise permissions check inside the controller to return a 400 for invalid operations. That'd be more properly RESTful anyways.

However there are 2 issues with the routes.rb. One is that we have the various episodes of care listed as top-level resources rather than resources nested under patient. A EoC w/o a patient is nonsensical. They were only in the routes.rb file because the default views generated by scaffold had a bunch of paths that expected a non-nested (top-level) resource. @MrJadaml removed bunches of that so we should go ahead and kill off the top level resources for each of those model objects.

**Comment by MrJadaml** [comment]
@awong-dev  I removed the Delete routes for now. They are in a resource `:except` and can be added back in really easy when we create admin users if we want to do it that way. I can also just update the PR and add them back in now if you'd like.

Fixed in PR #60

**Comment by awong-dev** [comment]
Thanks @MrJadaml!  Closing.

**Comment by awong-dev** [comment]
Accidental reopen. Closing again.
