### ISSUE TITLE
Ensure there is a clean SSN list

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#68]
Creating issue for tracking.

**Comment by awong-dev** [comment]
@philullrich Was there any progress on this over the past week?

**Comment by philullrich** [comment]
When we are ready to shut down SCIDO and move to use of interim system, we can have our contractor (Venkata) run a full SSN list.  We can cross-reference that with our 'delete list' thereby creating the clean SSN list.

**Comment by awong-dev** [comment]
Closing as we are no longer tracking clinic team tasks on the issue tracker.
