### ISSUE TITLE
Delete duplicate entries on SCIDO.

### ISSUE THREAD

**Issue by iamkevinscott** [department-of-veterans-affairs/SCIInterim#69]
Get ETA for the duplication removal.

**Comment by awong-dev** [comment]
Ping on this too...did we get an ETA?

**Comment by philullrich** [comment]
Kevin corresponded with the contractor (Venkata) handling this and he was told "Without delays or show stoppers , I would think this can be completed by end of July(at least my part of the work)."  Apparently he sends scripts to a national database team who then deletes entries.

**Comment by iamkevinscott** [comment]
@awong-dev I will speak with Venkata and figure out if there is a way to expedite this.  End of July does not sit well with me.  I will request POCs for the other parties involved in running the DB scripts.  Punting this over to m4.

**Comment by awong-dev** [comment]
Closing all non dev-team related issues since they aren't being tracked by github anymore.
