### ISSUE TITLE
Use anchor tags for links to patient details

### ISSUE THREAD

**Issue by huttj** [department-of-veterans-affairs/SCIInterim#84]
Per [my comment](https://github.com/awong-dev/SCIInterim/commit/3b99aee9e6f99511c69188b5cef30972fa2b9e37#commitcomment-11277783):

> I would highly suggest making everything that is a link into an actual link. Using JS for links means that certain features are broken (right-clicking, middle-clicking, tabbing through links, etc).
> 
> Is there a particular reason to use JS in this case?

**Comment by huttj** [comment]
I figured out the reason--it's to make the whole row clickable.

I think a good balance can be struck by adding a link to the patient's name, like so:

```
td: a href="#{edit_patient_path(patient)}" = patient.name
```

[patients\index.html.slim:15](https://github.com/awong-dev/SCIInterim/blob/6319a771e3e1fa0a1c6116c5aebdbdbb41d2417b/app/views/patients/index.html.slim#L15)

**Comment by awong-dev** [comment]
oh right...yes, that's what I was trying to do.  If you add an anchor there as well, that means we get a hybrid experience which I think I'm good with.
