### ISSUE TITLE
Add specs for UI behavior

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/SCIInterim#9]

**Comment by awong-dev** [comment]
@huttj @MrJadaml 

I added basic feature tests for rspec.  For all future changes, please try to add a feature spec using capybara to assert the major functionality you might be implementing.

**Comment by MrJadaml** [comment]
@awong-dev I added feature tests for Sign-up #61

**Comment by awong-dev** [comment]
Basic testing patterns established. Closing.
