### ISSUE TITLE
consolidate reports into single view (perhaps with tabs or accordion)

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/SCIInterim#93]

**Comment by awong-dev** [comment]
We punting until we have more requirements or is there going to be motion on this in m3?

**Comment by emilyville** [comment]
Yeah, works for me. I'll take a stab at making the UX for reports a little more intuitive but I think we need more information about reports before moving forward.

**Comment by emilyville** [comment]
closing since this is no longer part of the plan.
